In [1]:
import pandas as pd

In [2]:
uninsured_df = pd.read_excel('clean_data/insurance_coverage_by_state_by_year.xlsx')

In [3]:
uninsured_df.head()

,Year,Nation/State,Coverage,Estimate,Margin of Error,Percent,Margin of Error.1
0,2018,UNITED STATES,Total,322249,15,100,Z
1,2018,UNITED STATES,Any coverage,293684,178,91.1,0.1
2,2018,UNITED STATES,Uninsured,28566,183,8.9,0.1
3,2018,UNITED STATES,Private,217623,404,67.5,0.1
4,2018,UNITED STATES,..Employer-based,177740,354,55.2,0.1

In [4]:
uninsured_df = uninsured_df.loc[uninsured_df['Coverage'] == 'Uninsured',:]
uninsured_df = uninsured_df.loc[uninsured_df['Year'] <= 2010,:].sort_values('Year').reset_index()
uninsured_df = uninsured_df[['Year','Nation/State','Percent']]
uninsured_df = uninsured_df.rename(columns={'Year':'poll_year','Nation/State':'location','Percent':'rate_of_uninsured'})

In [5]:
uninsured_df.to_csv('clean_data/uninsured.csv')

In [6]:
uninsured_df

     poll_year              location rate_of_uninsured
0         2008               WYOMING              13.7
1         2008         MASSACHUSETTS               3.9
2         2008              MARYLAND              10.8
3         2008                 MAINE              10.4
4         2008             LOUISIANA                17
5         2008              KENTUCKY              13.2
6         2008                KANSAS              11.4
7         2008                  IOWA               8.7
8         2008               INDIANA              13.4
9         2008              ILLINOIS              12.4
10        2008                 IDAHO              17.2
11        2008              MICHIGAN                11
12        2008               GEORGIA              18.2
13        2008  DISTRICT OF COLUMBIA               7.6
14        2008              DELAWARE                10
15        2008           CONNECTICUT               8.8
16        2008              COLORADO              16.7
17        2008            CALIFORNIA              17.3
18        2008              ARKANSAS              17.1
19        2008               ARIZONA                18
20        2008                ALASKA              19.1
21        2008               ALABAMA              13.3
22        2008         UNITED STATES              14.6
23        2008               FLORIDA              20.2
24        2008             MINNESOTA               8.4
25        2008                HAWAII               6.5
26        2008              MISSOURI              12.4
27        2008           MISSISSIPPI                17
28        2008         WEST VIRGINIA              14.8
29        2008            WASHINGTON              12.5
..         ...                   ...               ...
126       2010             MINNESOTA               9.1
127       2010                HAWAII               7.9
128       2010           MISSISSIPPI              18.2
129       2010              OKLAHOMA              18.9
130       2010               MONTANA              17.3
131       2010               WYOMING              14.9
132       2010             WISCONSIN               9.4
133       2010         WEST VIRGINIA              14.6
134       2010            WASHINGTON              14.2
135       2010              VIRGINIA              13.1
136       2010               VERMONT                 8
137       2010                  UTAH              15.3
138       2010                 TEXAS              23.7
139       2010             TENNESSEE              14.4
140       2010          SOUTH DAKOTA              12.4
141       2010        SOUTH CAROLINA              17.5
142       2010          RHODE ISLAND              12.2
143       2010          PENNSYLVANIA              10.2
144       2010                OREGON              17.1
145       2010                  OHIO              12.3
146       2010          NORTH DAKOTA               9.8
147       2010        NORTH CAROLINA              16.8
148       2010              NEW YORK              11.9
149       2010            NEW MEXICO              19.6
150       2010            NEW JERSEY              13.2
151       2010         NEW HAMPSHIRE              11.1
152       2010                NEVADA              22.6
153       2010              NEBRASKA              11.5
154       2010              MISSOURI              13.2
155       2010         UNITED STATES              15.5

[156 rows x 3 columns]